name: "create examples"

on:
  workflow_dispatch:
  push:
    branches: ['main', 'dev-*']
  pull_request:
  release:
    types: [published]

jobs:
  create-examples:
    name: "Example"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Remove current example
        run: |
          rm -rf examples/coffeeratings/*
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r examples/requirements.txt
          python -m pip install .
          python examples/coffeeratings.py
      - name: Git diff
        run: |
          git diff
