name: "create examples"

on:
  workflow_dispatch:
  push:
    branches: ['main', 'dev-*']
  pull_request:
  release:
    types: [published]

jobs:
  create-example:
    name: "Example run"
    runs-on: ubuntu-latest
    steps:
      - run: |
        python -m pip install --upgrade pip
        python -m pip install requirements/dev.txt
        python examples/coffeeratings.py
        
      - run: | 
        git diff
